name: Deploy to AWS
run-name: "Deploy to AWS (Branch: ${{ github.ref_name }})"

concurrency:
  group: deploy-main
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    # AWSへのDeployは承認必須とする
    environment: production

    steps:
      # 最新mainチェック用にリポジトリを取得
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得

      # 承認したDeployが最新mainでなければ実行しない
      - name: Deploy only if latest main commit
        shell: bash # パイプライン途中のエラーも確実に検知
        run: |
          set -euo pipefail
          git fetch origin main
          # 最新のmainのSHAとDeploy対象のSHAを比較
          LATEST_MAIN_SHA=$(git rev-parse origin/main) 
          # 手動実行した場合はgithub.event.workflow_runが存在しないため、その場合はgithub.shaを使用
          TARGET_SHA="${{ github.sha }}"
          echo "Latest main SHA: ${LATEST_MAIN_SHA}"
          echo "Target deploy SHA: ${TARGET_SHA}"
          if [ "${LATEST_MAIN_SHA}" != "${TARGET_SHA}" ]; then
            echo "Target deploy commit is not the latest main commit. Failing to prevent stale deploy."
            exit 1
          fi

          echo "The target deploy commit is the latest main commit. Proceeding with deployment."

      # EC2へDeploy実行
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash ~/BlogApi/infra/utilitys/deploy/deploy.sh
          command_timeout: 30m
          timeout: 60s

  notify:
    needs: [deploy]
    if: always()
    uses: ./.github/workflows/slack-notification.yml
    with:
      status: ${{ needs.deploy.result == 'success' && 'success' || 'failure' }}
      source: "Deploy to AWS"
      branch: ${{ github.ref_name }}
      run_id: ${{ github.run_id }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
