name: Generate Swagger Docs

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      pr_branch:
        required: true
        type: string
  workflow_dispatch:

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pr_branch }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init -g main.go -o docs/swagger
      
      - name: Commit and push docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/swagger/
          if ! git diff --cached --quiet; then
            git commit -m "Update Swagger docs [skip ci]"
            git push origin HEAD
            echo "Swagger docs updated"
          else
            echo "No updates to Swagger docs"
          fi

